service: bz-data

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

package:
  include:
    - ../node_modules

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ../webpack.config.js
    includeModules:
      packagePath: ../package.json

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: us-west-2
#  environment:
#    DB_NAME: ${ssm:/bluezone/${opt:stage}/postgres/db}
  apiGateway:
    restApiId:
      'Fn::ImportValue': apiGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': apiGateway-rootResourceId
  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter*
      Resource: 'arn:aws:ssm:us-west-2:*:parameter/*'
    - Effect: Allow
      Action:
        - cognito-idp:AdminListGroupsForUser
        - cognito-idp:AdminAddUserToGroup
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminGetUser
      Resource:
        'Fn::ImportValue': CognitoUserPool-arn
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'

functions:
  migrate:
    handler: migrate.main
    description: Used for any bulk data changes
    timeout: 120
    events:
      - http:
          path: migrate
          method: get
          cors: true
          authorizer: aws_iam
