service: bz-public

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

package:
  include:
    - ../node_modules

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ../webpack.config.js
    includeModules:
      packagePath: ../package.json

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: us-west-2
  environment:
    STAGE: ${opt:stage}
    DB_NAME: ${ssm:/bluezone/${opt:stage}/postgres/db}
    DB_HOST: ${ssm:/bluezone/${opt:stage}/postgres/host}
    DB_USER: ${ssm:/bluezone/${opt:stage}/postgres/user}
    DB_PASS: ${ssm:/bluezone/${opt:stage}/postgres/pass}
  apiGateway:
    restApiId:
      'Fn::ImportValue': apiGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': apiGateway-rootResourceId
  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter*
      Resource: 'arn:aws:ssm:us-west-2:*:parameter/*'
    - Effect: Allow
      Action:
        - cognito-idp:AdminListGroupsForUser
        - cognito-idp:AdminAddUserToGroup
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminGetUser
      Resource:
        'Fn::ImportValue': CognitoUserPool-arn
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'

functions:
  legislator:
    handler: legislator.router
    description: Public endpoints for accessing legislator data
    events:
      - http:
          path: public/legislator
          method: get
          cors: true
      - http:
          path: public/legislator/{action}
          method: get
          cors: true
      - http:
          path: public/legislator/{action}/{id}
          method: get
          cors: true
  state:
    handler: state.router
    description: Public endpoints for accessing state data
    events:
      - http:
          path: public/state
          method: get
          cors: true
      - http:
          path: public/state/{action}
          method: get
          cors: true
      - http:
          path: public/state/{action}/{id}
          method: get
          cors: true
